### ISSUE TITLE
Could I concatenate {{> afQuickField name='item.{{index}}.name' }}?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-autoform#1122]
I would like to concatenate `field name` like this
```js
{{#each data}}
   {{> afQuickField name='item.{{index}}.name'}}
   {{> afQuickField name='item.{{index}}.qty'}}
   {{> afQuickField name='item.{{index}}.price'}}
{{/each}}
```
Please help me.

**Comment by abecks** [comment]
You could do this with a helper:

```handlebars
{{#each data}}
   {{> afQuickField name=fieldName}}
{{/each}}
```
```js
Template.myTemplate.helpers({
    fieldName: function(){
        return 'item.' + this.index + '.name';
    }
});
```

But I think you'll require a helper for each name you want to pull. Where does ```index``` come from?

**Comment by thearabbit** [comment]
Very thanks for your helping.

**Comment by jneuendorf** [comment]
Hi,

I have the same intention but a little different template structure.

```Handlebars
{{#each entries}}
    <tr><td>
        {{#Modal title="Edit entry"}}
            <!--
            expected: provide the index to all inner templates (=> to the form),
            observed: can't get passed #autoForm
            -->
            {{#let entryIndex=@index}}
                <!-- entryIndex is correct here -->
                {{#autoForm id=(concat "editEntry" @index) type="update" collection=... doc=... setArrayItems=true}}
                    <!-- entryIndex is empty here, @index would of course throw an error -->
                    {{> afFormGroup name=(concat "entries." entryIndex ".date")}}
                {{/autoForm}}
            {{/let}}
        {{/Modal}}
    </td></tr>
{{/each}}
```

The `concat` helper looks like this:

```javascript
Template.registerHelper("concat", function() {
    // last argument is the spacebar keyword hash
    return Array.prototype.slice.call(arguments, 0, -1).join("");
});
```

The `Modal` Template just creates a bootstrap modal with a title and the form as its content.

As described in the HTML comments the declaration of `entryIndex` with `{{#let}}` works but the variable is not accessible in the `#autoForm` block (which I would expect due to the meteor docs and http://stackoverflow.com/a/32730955).
Also, `@index` is still accessible within `#Modal` (so apparently generally `{{#let}}` seems to make variables visible in inner blocks?!).

**How can I get the index of the current iteration inside the `autoForm` template so I can create my modals dynamically?**

Thanks in advance!
