### ISSUE TITLE
Feature: Theming packages for autoform

### ISSUE THREAD

**Issue by cyrus-za** [aldeed/meteor-autoform#1298]
I am still new to autoform and haven't used it that much (using mostly angular-meteor), but I was thinking, instead of defining html elements seperately and adding things like bootstrap-datepicker, would it not be nice to have theming packages?

e.g. have a default package `aldeed:autoform` and then install `twbs:bootstrap-autoform` which depends on `aldeed:autoform` and then overwrites some of the code to generate a standard bootstrap form with all the classes such as  `btn success`, `form-input`, `form-group`, `row` and `col-md-4` etc. 

Then if you got a project that uses bootstrap and you want to migrate it to some new trend, e.g material-design, you would simply go and install this new package `autoform:material-design` or whatever it might be called and without changing any html files or any code in the project, all forms magically update to material design. 

Like I said at the top, I am still new to autoform and I don't know if it is practically possible to have packages that overwrite the autoform functionality and still stay up to day with versioning, but I figured it would be a good idea to look into it and it will help with the lifespan of autoform to live in production as opposed to the current usage of prototyping (and some admin routes where styling doesnt matter). 

Right now, css can only do so much without the actual html content changing. 

Just my 2 cents. Use it, don't use it :)

**Comment by aldeed** [comment]
This is pretty much how it already works, except that the `bootstrap` theme package is currently included with the core package. Pulling that out into its own package is near the top of my to do list. Anyone can already create a theme package for any other framework.

Theme packages are currently primarily for overall form layout and default HTML field types. There isn't really a way to swap custom components just by swapping the theme package. One idea might be to document a standard component naming convention. For example, various autoform theme packages would all define advanced components with identical type names, so you could do `type="DateTimePicker"` for your form field and then simply swap theme packages to get variations of a date time picker. It seems like a good idea in theory, but in practice I suspect it won't work that well since many components would require additional packages. I don't know if it is worth the coordination effort.
