### ISSUE TITLE
Meteor 1.3 method importing

### ISSUE THREAD

**Issue by Bandit** [aldeed/meteor-autoform#1466]
**I don't understand how to `import` my methods so that AutoForm can see them.** Based on the 1.3 best practices, all inserts/updates/deletes should be blocked on the client, and we should use methods instead. These should be imported on a page-by-page basis on the client.

I tried making a helper (along the same lines as #1449) but this returns an error `method.js:11 Uncaught Error: When form type is "method", you must also provide a "meteormethod" attribute`.

I guess I could include all methods on all client pages on startup, but according to the guide this isn't recommended. So what's the best practice for this? How do I tell AutoForm where to find my method?

**Comment by Bandit** [comment]
I solved my own problem. Replying here for posterity because there is a serious lack of information about this kind of thing.

Don't `import` anything, just reference the **internal `Meteor` method name** in AutoForm's `meteormethod` attribute.

For example (if you're using `ValidatedMethod`):

```
export const insertProject = new ValidatedMethod({
  name: 'projects.insert',
  validate: Projects.schema.validator(),
  run(fields) {
    Projects.insert(fields);
  }
});
```

You'd then use:

```
{{> quickForm collection=projects id="insertProjectForm" type="method" meteormethod="projects.insert"}}
```

Ref: https://themeteorchef.com/snippets/using-validated-methods/

**Comment by DanielDornhardt** [comment]
Man, this is great. I never thought this would work, didn't even believe before I tried it. Non-Obvious, I think - I was flummoxed because the ValidatedMethods expect named parameters and autoform normally sends the whole document as a parameter - I didn't think that the first parameter that autoform sends would be the same parameter used by ValidatedMethods as the dictionary of values to validate...

Really great! :D

Here's an explanation on how to do the same thing for forms of type "method-update", for anyone who's wondering:

https://github.com/meteor/validated-method/issues/18
