### ISSUE TITLE
Upgrade to 7.0.0

### ISSUE THREAD

**Issue by jankapunkt** [aldeed/meteor-autoform#1692]
We should focus now on updating AutoForm to v7, which has already been implemented by @pouya-eghbali for personal usage.

@pouya-eghbali maybe you just start a PR using your latest stable branch, in the meantime we can all discuss some requirements for review and then start reviewing the PR?

**Comment by pouya-eghbali** [comment]
Working on it.

**Comment by pouya-eghbali** [comment]
I created #1693 
It needs review, readme.md should be updated, documentation should be updated, and a lot of other things needs to be done.

**Comment by pouya-eghbali** [comment]
btw #1296 is included in #1693 
it also fixes a lot of the issues reported, sadly i didn't keep track of those.

**Comment by jankapunkt** [comment]
Thank you for the fast response. I am still a bit off work so I can make some tests and create a review.

I have currently about 10 extensions and a mid sized project that heavily rely on AF so I should get some fast results if there are any compatibility issues.

Since we have no tests (yet) we may create a custom testing / qa list:

|test|related issues|optional comments|
|---|---|---|
|works with latest Meteor|#1688||
|works with Meteor 1.x||how far we need to support backwards compatibility?|
|works without `underscore`||is it even possible to have underscore removed while using Blaze?|

Maybe you extend this table with some of the features you can clearly name since they were important part of your rework etc. I think there were also some [issues](https://github.com/pouya-eghbali/meteor-autoform/issues?q=is%3Aissue+is%3Aclosed) you already closed so we can complete this table.

What do you think?

**Comment by jankapunkt** [comment]
@pouya-eghbali which templates do you use? Do you use `plain` or some custom set? I just tried to include my bs4 templates and they don't work unless I first add the deprecated bs3 templates. I am just curious which ones you use and how you integrated them.

Nevermind, I already found the issue - the bs4 templates inherit some helpers from the bs3 templates.

**Comment by pouya-eghbali** [comment]
Sorry I've been really busy the past few days. I use a forked / custom version of mozfet:autoform-materialize.

I tried to log every change I make in the readme file [here](https://github.com/pouya-eghbali/meteor-autoform).

I'd like to make a few notes here:

* Features I added, like setFieldValue, work, but are not perfect, they probably need more work if we're merging them here.

* I redid how ArrayTracker works, but kept the old ArrayTracker implementation because I didn't want to break things, this can be cleaned up in a v7 release.

* I made several functions that are used a lot in AutoForm, like isObject or isFunction, however they're not used everywhere, we still have a lot of `typeof xyz === "function"` in our code. 

* I use prettier, some files are properly formatted (the ones I touched), the others are in their original format. I propose using prettier, if you suggest something else it's fine by me.

* I did a lot of performance fixes, and tried my best to find and remove bugs caused by them, but they may still have some bugs.

* I rewrote some stuff in ES6 format, but there are a lot of things that are still ES5. The combination of `var` and `const` keywords looks a little weird, there are a lot of for loops that can be replaced with for of or for in, and there are a lot of things that can be replaced with map, filter, forEach, and reduce.

I have a huge app and I heavily depend on autoform to render user created custom schemas (Using some kind of form builder). When I find an issue in autoform I find it and fix it, that's how I did this so far, from now on I'm going to push to my own repo and then make pull requests here.

There are tons of open issues and PRs, how should we deal with them?

**Comment by jankapunkt** [comment]
> Features I added, like setFieldValue, work, but are not perfect, they probably need more work if we're merging them here.

Did you add tests for these features? If not, do you think it will interfere with your current work to add tests?  I could support in setting up the testing environment, if you need help there.

> I redid how ArrayTracker works, but kept the old ArrayTracker implementation because I didn't want to break things, this can be cleaned up in a v7 release.

> I made several functions that are used a lot in AutoForm, like isObject or isFunction, however they're not used everywhere, we still have a lot of typeof xyz === "function" in our code.

> I use prettier, some files are properly formatted (the ones I touched), the others are in their original format. I propose using prettier, if you suggest something else it's fine by me.

I think these are things, we should discuss as team @Meteor-Community-Packages/autoforms 
@ricaragao also asked for a strategy / roadmap in the team

> I did a lot of performance fixes, and tried my best to find and remove bugs caused by them, but they may still have some bugs.

Is it difficult to write tests for them to prevent regression in the future?

> I rewrote some stuff in ES6 format, but there are a lot of things that are still ES5. The combination of var and const keywords looks a little weird, there are a lot of for loops that can be replaced with for of or for in, and there are a lot of things that can be replaced with map, filter, forEach, and reduce.

I think this is a mid- to long term goal but I also suggest to discuss this as team.

> I have a huge app and I heavily depend on autoform to render user created custom schemas

This is for me the same and we have many custom extensions already written. Nice to know: they worked flawlessly and required only slight changes with your pr #1693
