### ISSUE TITLE
Rendering update forms for all docs in a collection

### ISSUE THREAD

**Issue by ghost** [aldeed/meteor-autoform#278]
Can you demonstrate the correct way to go about this? I'm trying to loop over all the docs returned by a query and render an update form for each. In this case it's not clear what to pass as the doc. 

![screenshot from 2014-07-25 14 43 50](https://cloud.githubusercontent.com/assets/3188728/3707972/6650cd40-143c-11e4-8f65-3c3666cc8ef5.png)

![screenshot from 2014-07-25 14 44 39](https://cloud.githubusercontent.com/assets/3188728/3707980/85b83c36-143c-11e4-85f7-20a03b431914.png)

**Comment by emmanuelbuah** [comment]
@aldeed Since hooked are designed to be defined top level, how do we handle hooks for multiple update forms where we need to define the hooks dynamically using the course id (using the sample in this ticket) for the form name. e.g.

```
 AutoForm.addHooks("updateCourse-" + courseId, {
   ...
})
```

Especially if hook functions use/depend do template specific properties. I might be thinking about this all wrong but I keep running into cases where the hooks needs to be defined dynamically and if so, it cannot be top level.

**Comment by vhf** [comment]
I got the exact same problem as @emmanuelbuah. I would like to dynamically display multiple forms on a page, and have hooks on them.

My current use case is a calendar in which you can add events. One 'add event' (autoform insert) by time period. These forms need hooks.

I'll look at the code, and if it seems feasible I'll submit a PR to allow using IDs OR classes as hooks selectors.

**Comment by marktomm** [comment]
@vhf You need identical hooks for all/many forms?

**Comment by vhf** [comment]
Yep. Populating stuff without relying on hidden fields.
