### ISSUE TITLE
Unchecked checkbox behavior question

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-autoform#504]
Let's say I have a "sticky" Boolean represented by a checkbox. Checking the checkbox should mark it as `true`, but what about leaving the checkbox unchecked? Should it set the property to `false`, or else not set it at all?

I'm asking because in my current implementation, leaving the checkbox unchecked when inserting a document leaves the property unset, but doing the same when _editing_ a document marks it as `false`. Although I'm not sure if this is because of Autoform or something else in my code…

**Comment by aramk** [comment]
@aldeed I'm getting an issue where two seemingly identical collections have a boolean field with `defaultValue: true` but only one of the forms has the checkbox in the checked state when inserting.

The collections are [here](https://github.com/aramk/meteor-sandbox/tree/master/collections). Products and Colors have the `isBright` boolean. It only works for the [colorItem](https://github.com/aramk/meteor-sandbox/blob/master/client/views/colorItem.js) template but not [productItem](https://github.com/aramk/meteor-sandbox/blob/master/client/views/productItem.js).

**Comment by aldeed** [comment]
@aramk, the Products form is calling `AutoForm.resetForm` on rendered, which is clearing it. I'm not entirely sure why the browser clears the checkbox when you reset the form, even though it has the checked attribute. I found the prescribed behavior [here](http://www.w3.org/html/wg/drafts/html/master/forms.html#attr-input-checked):

> The reset algorithm for input elements is to set the dirty value flag and dirty checkedness flag back to false, set the value of the element to the value of the value content attribute, if there is one, or the empty string otherwise, set the checkedness of the element to true if the element has a checked content attribute and false if it does not, empty the list of selected files, and then invoke the value sanitization algorithm, if the type attribute's current state defines one.

This is a bit difficult to parse, but it seems to me that it should be retaining the checked state on reset. It's possible this is an issue that could be fixed in Blaze, but you'd have to recreate the issue without autoform involved. Autoform is simply calling form.reset(), so I'm hesitant to do any specific overrides of that behavior.

All of that being said, I don't think there's any reason why you should have to reset the form on render.

**Comment by aramk** [comment]
Hi @aldeed, thanks for that clear and detailed explanation, I think that's in indeed the case. Cheers!
