### ISSUE TITLE
Dynamically changing form schema

### ISSUE THREAD

**Issue by abecks** [aldeed/meteor-autoform#600]
I have a use case where I need to change the fields in a form dynamically, removing, replacing, and adding new fields to the form.

I'm currently using a ReactiveVar to keep track of the schema, and replacing it with a new schema in order to update the form. When I do so, Autoform throws exceptions for the old, now non-existant fields: 

```
Exception in template helper: Error: Invalid field name: questionOne
```

Would you recommend changing the schema on the form this way, or re-rendering the form's container template?

**Comment by KrishnaPG** [comment]
Same problem here as @abecks . Thank you for the `destroyForm` workaround. But, unfortunately the semantics of `destroyForm` are not clear.

What is its scope and how it is supposed to prevent the problem: I can see from the sample code that whenever the schema is updated (set) `destroyForm` was set to true. But how does this solve the problem and when is the right time to set it false again?

I see the this.autorun() setting it to false, but does it need to get called in particular sequence (such as first autoform should execute then autorun should execute etc.) - because I tried to mimic your example and having problem getting success.

**Comment by aldeed** [comment]
Every time you toggle destroyForm on, the autorun turns it back off. Set it to true right before you change the form's schema attribute value.

**Comment by KrishnaPG** [comment]
I tried the `destroyForm` approach - it was buggy for me, couldn't make it work (timing issues, the firing order of callbacks matter a lot).

Anyhow - removed it and got away with dynamic templates for creating new autoforms (with new schema) automatically whenever the schema changes.

**Comment by pdiniz13** [comment]
I dont understand why this was closed. The destroyForm approach is not ver well documented, and I'm not sure how we are supposed to use it.

**Comment by aldeed** [comment]
Pretty sure dynamic schemas should work fine without this workaround in more recent autoform versions.

**Comment by sayanriju** [comment]
Not sure if this is still working 100%.
The UI seems to work as intended, and the fields in data being inserted also seems to be ok, but the exceptions are still being fired on the console.

**Comment by evanglerm** [comment]
Hi Guys any one of u got this Dynamic thing working with Ionic ? Please share detail/workaround to get it working with ionic. 
Thanks
