### ISSUE TITLE
Error: afQuickField must be used within an autoForm block

### ISSUE THREAD

**Issue by KrishnaPG** [aldeed/meteor-autoform#605]
While trying to use `bootstrap3-horizontal` template with `afFieldNames` getting the below error:
````
afQuickField must be used within an autoForm block
````
Below is the code that is causing trouble:
````
{{#autoForm schema=contactFormSchema id="contactForm" template="bootstrap3-horizontal"}}
	<fieldset>
		<legend>Data Definition</legend>
		{{#each afFieldNames}}
		   {{> afQuickField name=this options=dataTypeOptions}}
		{{/each}}
	</fieldset>
{{/autoForm}}
````
The same above code has no problem if `template="bootstrap3-horizontal` is removed.

How to make `autoForm` work with `bootstrap3-horizontal` and `afFieldNames`?

**Comment by Firfi** [comment]
Is there reason why is it closed? Did you find a solution?

**Comment by KrishnaPG** [comment]
The problem was happening because of some problem in my code (and not with the package). 

I was incorrectly using the template name and arguments, was causing the problem.

**Comment by Firfi** [comment]
I had similar problem just now but it seems if was different issue. I'll leave solution if someone is searching it:

Real issue was I had two same autoforms with same ID's in one DOM. One was a main auth page and second is popup auth that I show on some another pages Both were rendered. Now I just don't render popup auth modal for auth page (hiding it with something like `#if` block)
