### ISSUE TITLE
Add initialValue option for update forms

### ISSUE THREAD

**Issue by fusepilot** [aldeed/meteor-autoform#617]
When adding new items inside of array in an update form, Simple Schema defaultValues for those item's fields are ignored.

Here's a [repro](http://meteorpad.com/pad/tAaSDHMCcZLAeMgHB) on meteorpad.

I realize that this is might be because the array fields in the doc are empty when you click the add button. And it's just reflecting the doc's values which are currently nil for those fields. But I expected autoform to still respect the defaultValues since it behaves similarly to an insert form with arrays.

**Comment by aldeed** [comment]
I think we need to add an `initialValue` for update forms and cases like this. It's a bit different from a default value, especially since `defaultValue` is actually a simple-schema thing that autoform borrows.

**Comment by theduke** [comment]
+1, I need a initialValue for my fields too, since I can run into validation problems otherwise (use case: optional sub-documents with fields that have a defaultValue)

**Comment by chompomonim** [comment]
So, what is difference between initialValue and defaultValue? Or main problem is that defaultValue is already used in simple-schema and it would be hard to make it work in proper way?

**Comment by aldeed** [comment]
Right, autoform borrows defaultValue, but that creates a conflict between different expectations for it at the schema level vs. the form level. It would be cleaner to have an autoform-specific way. You can set the `value` attribute, but for an update form, that overrides the value that would otherwise be pulled from the doc.

So we need a way to say "use the value from `doc`, but if there isn't one, use X as the default".
