### ISSUE TITLE
Displaying form error message instead of individual fields

### ISSUE THREAD

**Issue by gussandy** [aldeed/meteor-autoform#636]
Hi aldeed, I'm trying to display form-wide error messages on the client instead of displaying them per field. Any ideas of I can accomplish this with autoform? See attach image.
![screen shot 2015-01-15 at 11 14 18](https://cloud.githubusercontent.com/assets/5196153/5756622/6b888fd2-9ca9-11e4-875b-ff0c6acdd44f.png)

On a separate note, is it better to use mySimpleSchem.addValidator(myFunction) when implementing manual validation instead of autoForm's AutoForm.validateForm(formId)? Your thought on these would be greatly appreciated.

**Comment by mlurz71** [comment]
If I may..As to your first question, use the afFieldMessage helper to display the error message for a specific field. To automate the display of error messages for a list of fields:
* Create a helper that returns the list of field names.
* Iterate over that list calling afFieldMessage on each field name.

As to your second question, the ss method you reference adds a custom validation function to **all keys** of a specific ss instance (which is probably not what you're looking for). To implement custom validation for a **specific key**, use the **custom option** on the schema definition for that key.

As to when to use the AutoForm validation methods and when to use the ss validation methods:
* Use the AutoForm validation methods when performing manual validation **inside of the context** of an AutoForm.
* Use the ss validation methods when performing manual validation **outside of the context** of an AutoForm.

Keep in mind that manual validation shouldn't be necessary in most cases. Here are a couple of examples where it may be needed:
* When using non-AutoForm elements inside of an AutoForm. In this case you may want to define a custom input type so that AutoForm is always working with AutoForm-aware elements.
* When you need to interact with an AutoForm from elements outside of the form.

**Comment by gussandy** [comment]
@mlurz71 thanks for your support...slowly getting the hang of autoform/ss. A related question I have is that, if I want to implement validation for a range of fields as per the image I earlier i.e. comparing inputs in one field against another ad rendering validation errMsg, what do u think my approach should be with autoform/ss?

**Comment by mlurz71** [comment]
The ss docs include an example for [validating one field against another] (https://github.com/aldeed/meteor-simple-schema/#validate-one-key-against-another). That should get you started.
