### ISSUE TITLE
Strange behavior when calling this.done()

### ISSUE THREAD

**Issue by fusepilot** [aldeed/meteor-autoform#639]
Here's a repro [meteorpad](http://meteorpad.com/pad/5jBfPiXFX4iGMRK5c).

When called on line 15 of client/app.coffee, the field values are reset. When called on line 12, the field values remain but the Log In button becomes disabled. I want to keep the field values intact until we've verified a successful login and be able to re-submit.

**Comment by aldeed** [comment]
The form is reset on successful submit, so that makes sense. (You can disable that with `resetOnSuccess=false` attribute, but you probably don't want to in this case.)

The only problem I see is that you're calling `@done()`, but you're within a new function context so `@`/`this` doesn't have a `done` function. You need to do `self=@` at the top of your `onSubmit` and then do `self.done()` within your callback. You need to be sure to call `self.done()` even when there is an error. If you don't, the button remains disabled.

**Comment by fusepilot** [comment]
Thanks for the response. I don't think that was the problem though since I was using =>, aka "[fat arrow](http://coffeescript.org/#fat-arrow)" which assigns @ to this at the point where it was defined. I'll be sure to use vanilla js in future issues.

I was able to make it work thanks to your tips by the following changes.
  • Set ````resetOnSuccess=false```` on the form.
  • Call just ````@done()```` on callback success.
  • Call both ````@resetForm()```` and ````@done()```` on callback error.

Thats easy enough for me.
