### ISSUE TITLE
Infinite loop with input mask and autosave on

### ISSUE THREAD

**Issue by fusepilot** [aldeed/meteor-autoform#647]
Here's a [meteorpad](http://meteorpad.com/pad/Mv5FFPnK3GPYeobRt) showing the problem.

I'm getting a infinite loop when applying a jquery.inputmask to an input with autosave on. The mask works fine autosave is not on. Goal is to apply a currency mask to an input field and then convert the value from dollars to cents to store in the database.

Chrome shows ````<error>````. Firefox shows ````too much recursion````.

**Comment by aldeed** [comment]
Not really sure what the cause is at the moment.

**Comment by chompomonim** [comment]
I'm also getting infinite loop when autosave=true.

**Comment by aldeed** [comment]
I put in a rather kludgy workaround for this issue, which seems to be more of a jquery.inputmask issue with firing 'change' even though the value is the same, but it's still good to try to guard against it in autoform.

As far as getting it to work properly otherwise, this seems to work best for me:

```coffeescript
AutoForm.addInputType "price",
  template: "price"
  valueIn: (val) ->
    val / 100 # convert to dollars
  valueOut: ->
    @val() * 100 # convert to cents

Template.price.rendered = ->
  $input = @$("input")
  $input.inputmask inputMaskOptions
  
  @autorun ->
    data = Template.currentData()
    $input.val(data.value) if data
```

And then remove `value={{value}}` from the template.

Consider making an add-on package with this input in it so that others can use it more easily. If you do, I can add it to the list in the readme.

**Comment by aldeed** [comment]
Done in AutoForm 5.0, now released.

**Comment by fusepilot** [comment]
Awesome, thanks @aldeed!
