### ISSUE TITLE
Why afFieldInput?

### ISSUE THREAD

**Issue by comerc** [aldeed/meteor-autoform#652]
```coffee
tags:
  type: [String]
  autoform:
    type: "selectize"
    afFieldInput:
      multiple: true
      selectizeOptions: {}
```
equal
```coffee
tags:
  type: [String]
  autoform:
    type: "selectize"
    multiple: true
    selectizeOptions: {}
```
Is it true, if I do not use afFieldInput?

**Comment by aldeed** [comment]
It first looks for specific object and then looks immediately within `autoform` object. If the attribute causes different behaviors on different components, then it's safer to put it under the specific component name object.

Also, if it is an attribute that you want added to the HTML (like `class`), then it's safer to put it under the correct component name so that it does not get added to all components.

But otherwise, yes they are equal.
