### ISSUE TITLE
Is there a "rendered" callback for autoform?

### ISSUE THREAD

**Issue by devinmooers** [aldeed/meteor-autoform#688]
I'm trying to execute some jQuery code on an autoform after it renders fully, but the template that my autoform is in fires its rendered callback before the autoform actually gets populated with data. It's an "update" form. 

Is there any kind of hook or callback from within autoform that will tell me when the data has been populated inside of the autoform?

**Comment by aldeed** [comment]
You could define a `rendered` callback for `Template.autoForm` and check `this.data.id` to see which form it is. I'd recommend using `aldeed:template-extension` pkg `hooks` method so that you don't inadvertently override any life cycle callbacks defined by the package itself. In the next Meteor release, you can simply do `Template.autoForm.onRendered(func)` because templates will support multiple callbacks natively.

**Comment by devinmooers** [comment]
Awesome, thanks! I'll use your template-extension pkg until then. Which Meteor release is this going to happen in?

**Comment by aldeed** [comment]
The next release (https://github.com/meteor/meteor/blob/devel/History.md). I don't know what the version will be or when they will release.

**Comment by devinmooers** [comment]
Got it, thanks!

**Comment by ChenRoth** [comment]
for current readers of this issue, Meteor 1.0.4+ supports Template.onRendered callback registering

**Comment by pihyper** [comment]
Yes, i dont think the template-extension package is needed any more, but it served its purpose anyway.
