### ISSUE TITLE
Set Checked Boxes Values

### ISSUE THREAD

**Issue by nspangler** [aldeed/meteor-autoform#760]
I want users to revisit their forms and see the values that they have previously entered. This works great using the `doc` parameter of the form. However for check box instances the old values are not set, but I confirm that they are changed upon update of the collection. Is this a known problem or is there a fix?

**Comment by aldeed** [comment]
This worked last I checked. You'll have to post a link to a repo that shows the issue. Could be related to Blaze handling of check boxes.

**Comment by Jehu** [comment]
Same problem here since last Meteor update.

After reading #777 and #765 a quick test with a temporary helper Checkbox values are set again.

```javascript
getWeekdays: function() {
    var wd = [];
    for (index in this.congDoc.trolleyConfig.weekdays) {
      wd.push(this.congDoc.trolleyConfig.weekdays[index]);
    }
    return wd;
  }
```

```jade
 +afFormGroup name="trolleyConfig.weekdays" value=getWeekdays
```

**Comment by SachaG** [comment]
I'm also running into the problem in Telescope: https://github.com/TelescopeJS/Telescope/issues/828

I'm not 100% sure, but it does seem like it's related to https://github.com/aldeed/meteor-autoform/issues/765, because I have two similar checkbox fields on the same page. 

One is stored as an array, and checkboxes are properly checked. Another is stored as an object, and checkbox aren't checked even though the object is updated in the database.

**Comment by SachaG** [comment]
Yep, I can confirm that after manually changing the object to an array containing the same values via the Meteor shell, the checkboxes got properly checked.

**Comment by aldeed** [comment]
Please retest with AutoForm 5.1.0 and close if your issue is resolved.

**Comment by SachaG** [comment]
Works for me at least. Thanks for the quick fix!

**Comment by nspangler** [comment]
It works great. Thanks.
