### ISSUE TITLE
Change autosaveOnKeyup throttle time

### ISSUE THREAD

**Issue by dkmooers** [aldeed/meteor-autoform#761]
500ms is a bit short - even with trimStrings=false, I'm still getting some deleted spaces while typing. I'd like to increase this to maybe 1000ms. It'd be great to have an autoForm attribute like `autosaveOnKeyupThrottleTime="1000"`.

**Comment by devinmooers** [comment]
I'm actually wondering if _.debounce would work better. That way it wouldn't save until after you've *stopped* typing (like 1000ms after stop, for instance). It wouldn't try to save as you're in the middle of typing. That may better prevent losing final characters while typing. Or maybe just being able to tweak the throttle time to ~1000ms would help me fix this issue.

With Google Docs, as soon as you start typing, the autosave status says "Saving..." but it only switches to "All changes saved" ~2000ms after you *stop* typing. It seems more like a debounce function than a throttle. Actually, it looks like it's using debounce for round-trips to the server, and throttle for saving locally (in localStorage or something). To test this, I edited a doc, mashed a bunch of keys and immediately hit the "back" button. When I re-opened the document, all the letters were there, but it popped up an "Syncing offline changes..." message. So it hadn't actually sent that data to the server yet, indicating they're probably using debounce to submit the data to the server and auto-save it. Anyway, the local storage thing isn't super relevant here, just that switching to debounce might prevent letters from getting cut off as you type (when using autosaveOnKeyup).

**Comment by aldeed** [comment]
All makes sense to me. We can play with it a bit more. If you want to do a PR for those changes, I can take a look. Ultimately we really need a smarter autosave (one that doesn't simply submit the form) but since there is so much that happens as part of a form submit, potentially changing the final field value that should be saved, it will take a lot of careful thought and design to move in this direction.

**Comment by devinmooers** [comment]
Update: I think the problem is actually Mongo trimming whitespace. it seems like trimStrings=false isn't actually having the desired effect. When I type a word into a textarea with autosaveOnKeyup, and then a bunch of spaces right after it (like `test     `), the full string with trailing spaces correctly gets passed to my "meteor-update" method. When I log the modifier from the meteor method, it correctly says `test     ` in the modifier. But when I check the Mongo database, it's saved as `test`, with all trailing spaces removed, instead of `test     `. Is there something about Mongo that trims trailing whitespace automatically? Even if I only type *one* space after `test`, it still cuts off the space when saving to Mongo. AutoForm passes the space through correctly (so trimStrings=false seems to work there), but Mongo's cutting it off. This leads to losing spaces while typing, when using autosaveOnKeyup. Any ideas?

**Comment by aldeed** [comment]
`trimStrings=false` works only if the form is doing the update. If your method is doing the update, then you need to pass the `{trimStrings: false}` option to the update call.

**Comment by devinmooers** [comment]
Ah! Wait, where do I add that option? In the meteor method?

Here's my form template code:

    +quickForm collection="Clients" type="method-update" meteormethod="editClient" id="edit-client-form" doc=this autosaveOnKeyup=true trimStrings=false buttonContent=false resetOnSuccess=false

And here's my update method:

    editClient: function(modifier, clientId) {
        console.log(modifier);
        check(modifier, ClientSchema);
        check(clientId, String);
        console.log(modifier);
        Clients.update({_id: clientId, manager: this.userId}, modifier);
        return false;
    }

For some reason, the client code *is* trimming strings, and the server code is *not*. On the client, both those `console.log(modifier)`s spit out trimmed strings, but on the server, both of them spit out non-trimmed strings. Shouldn't it be the opposite? The server is logging the *non-trimmed* strings, but then stores it in the Mongo db as trimmed.

**Comment by devinmooers** [comment]
Aha! Fixed this by adding "trim: false" to my SimpleSchema definition for the problematic textarea field.

**Comment by aldeed** [comment]
The call to `Clients.update` in your method automatically cleans. But you can tell it to skip different things:

`Clients.update({_id: clientId, manager: this.userId}, modifier, {trimStrings: false});`

**Comment by dkmooers** [comment]
Ah got it! Thanks. I tried that and this made autosave better, but still lost occasional characters so disabled it. It's not a huge deal - autosave would be nice to have at some point, but not the most necessary thing, I'm realizing, after trying it both ways. Also reduces server load to not have autosave firing every 500ms. :+1:
