### ISSUE TITLE
Multi-select selected options stored as object instead of array

### ISSUE THREAD

**Issue by garenor** [aldeed/meteor-autoform#765]
I have the following schema keys

````
"general.shipTypes": {
        type: Array,
        optional: true,
        // minCount: 1,
        label: "Selecteer de scheepstypes die van toepassing zijn",
        autoform: {
            firstOption: "(Selecteer scheepstypes, meerdere mogelijk)",
            placeholder: "Scheepstypes selecteren",
            type: "select2",
            multiple: true,
            options: function () {
                var result = [];
                shipTypes = TaxonomiesList.find({taxonomy: 'shipType'});
                shipTypes.forEach(function (shipType) {
                    result.push({label: shipType.name, value: shipType._id});
                });
                return result;
            },
            allowedValues: function () {
                var result = [];
                shipTypes = TaxonomiesList.find({taxonomy: 'shipType'});
                shipTypes.forEach(function (shipType) {
                    result.push(shipType._id);
                });
                return result;
            }
        }
    },
    "general.shipTypes.$": {
        type: String,
        optional: true,
    },
````

The data is saved as an object, but should be array. This was working pre 5.0. The modifier is as follows:

````
{ '$set': 
    {
        'general.shipTypes.0': 'WXweJeYpjaLFsGarG',
        'general.shipTypes.1': 'wBPLfC6xkS2FG5u2c'
    }
}

````

Any ideas?

**Comment by aldeed** [comment]
You are running into a mongo quirk (bug, in my opinion), where it is not smart enough to realize that a numeric key should create an array. Specifically

* If the modifier you posted is used and `general.shipTypes` is already an array in the database, it works.
* If the modifier you posted is used and `general.shipTypes` does not yet exist in the database or is `null`, it will create an object instead of an array.

Prior to AF5, we attempted to avoid this issue by always setting entire arrays. We always did:

```js
{ '$set': 
    {
        'general.shipTypes': ['WXweJeYpjaLFsGarG', 'wBPLfC6xkS2FG5u2c']
    }
}
```

However, the drawback is then we couldn't easily support forms where you want to update just a single array item. Forms always had to overwrite an entire array.

I anticipated this change might cause problems in cases like yours, but I wanted to get some real world example submitted before figuring out a solution, so if you can post the corresponding autoform, that would be helpful.

One simple solution could be to have a `keepArrays=true` attribute on the autoform, which would switch back to the old behavior. That feels a bit wrong, but it would probably work.

The way you can most likely solve your issue right now, without a new autoform release, is to restructure other parts of your code to ensure that `shipTypes` is always set to an empty array for every document.

**Comment by garenor** [comment]
That is a weird issue! You would expect that if you set a type to array in SS that it would save as an array, but it obviously does not. I want to set the shipTypes (a category list) to an array of strings (doc id's). I use methods to save the data, so i've written a few lines of code that checks if the `general.shiptypes` is an array or not, and update it accordingly. It works like a charm, but also feels a bit wrong... Maybe I come up with a better solution in the future.

**Comment by aldeed** [comment]
Reopening to track

**Comment by delgermurun** [comment]
I added `keepArrays=true` `quickFrom`. Like this `{{> quickFrom keepArrays=true ...}}`.

But nothing changes. Still getting object, not array.

**Comment by aldeed** [comment]
I haven't implemented keepArrays=true yet. Still figuring out the best way to handle this.

**Comment by aldeed** [comment]
Please retest with AutoForm 5.1.0 and close if your issue is resolved.

**Comment by lucatros** [comment]
I'm seeing this problem when using a schema like this one (array inside array):

```javascript
"book.$.authors": {
    type: [String],
    label: "Authors",
    optional: true
  },
```
I'll create a repo with this issue as soon as possible.
