### ISSUE TITLE
Are there no server side callbacks / hooks? 

### ISSUE THREAD

**Issue by NathanFig** [aldeed/meteor-autoform#773]
The client-side hooks (before, after, onSubmit, etc.) are nice, but is there no equivalent for the server side? 

I see the 'meteormethod' attribute, but that appears to only be called for method type forms. If I were to switch to method type, is there a simple way to call the insert or update chain of events from within meteormethod?

Thanks.

**Comment by aldeed** [comment]
If you submit to a method, the before.method and after.method hooks will be called. You don't really need before update, before insert, etc. because you're writing all the code in the method, so just do some stuff before or after you call `update` or `insert`.

Also, if you're doing anything more generic, not related to the specific form, then that's best handled in a collection hook, which can be defined on the server.
