### ISSUE TITLE
Help with custom input on arrays.

### ISSUE THREAD

**Issue by gabrielpoca** [aldeed/meteor-autoform#849]
Hi, I've been struggling to make this work, I searched intensively on the issue but I can't make this work. I have this schema.

```
  images: {
    type: [String],
    defaultValue: []
  },
  'images.$': {
    type: String,
    autoform: {
      type: 'thumbnail'
    }
  },
```

It's an array of ids. But instead of showing an input field I want to show the image that belongs to that id. I did the following.

```
Template.afThumbnail.helpers({
  image: function() {
    return Images.findOne(this.value);
  }
});

AutoForm.addInputType('thumbnail', {
  template: 'afThumbnail'
});
```

```
<template name="afThumbnail">
  <img class="img-responsive img-rounded" src="{{ image.url }}">
</template>
```

It shows the image correctly, no issue here. But when I click on the button to remove one of them from the array, it removes the whole array instead. And it was working before with the default text input. Thank you for your time.

**Comment by aldeed** [comment]
Probably because you are not providing any way to retrieve the input value from the "input", and you are not adding the provided attributes to it.

The simplest solution might be

```js
<template name="afThumbnail">
  <input type="hidden" value="{{this.value}}" {{this.atts}}/>
  <img class="img-responsive img-rounded" src="{{ image.url }}">
</template>
```

The only drawback is that any extra attributes you provide on the `afFieldInput` or in the schema will end up on the hidden input rather than on the visible `img`. If that's a problem, you could make some helpers that divide up `this.atts` and put some on the hidden input and others on the img. It's important that the `data-schema-key` attribute ends up on the `input`.

**Comment by gabrielpoca** [comment]
Thank you, it works. I was trying to write a `valueOut` function and everything, and it was this simple. I'll close the issue, thank you for your time.

**Comment by aldeed** [comment]
The trick is that if there is no `valueOut` function, it does `.val()` on whatever element has the `data-schema-key` attribute. Obviously `.val()` wouldn't work on an image element, but adding a hidden element makes the default logic work. You could have also stored the value in a `data-` attribute on the `img` and then added a `valueOut` that returns that.
