### ISSUE TITLE
Insert: doc value isn't having any effect

### ISSUE THREAD

**Issue by blainehansen** [aldeed/meteor-autoform#854]
I've documented this problem on [Stack Overflow](http://stackoverflow.com/questions/29417889/autoform-insert-doc-value-isnt-having-any-effect).

Essentially though, the `doc` argument for an `insert` autoForm isn't providing it's value when the insert actually happens.

**Comment by blainehansen** [comment]
I got my problem worked out, but it still seems to me that this line in the `doc` argument's explanation isn't living up to it's promises:

> For an insert form, you can also use this attribute to pass an object that has default form values set (the same effect as setting a value attribute on each field within the form).

**Comment by aldeed** [comment]
Yeah, the `doc` is used to set the initial value of any field *that is in the form*, but since you omit that field, no value is set. As you discovered, the correct way to do it is to keep it in the form but hide it with `type="hidden"`. Otherwise, you can set the value yourself in a "before insert" hook.

Please submit a pull request if you have ideas for improving the readme language.
